[package]
name = "parser-c"
version = "0.2.1"
authors = [
  "Tim Ryan <tim@timryan.org>",
  "Georg Brandl <georg@python.org>",
]
description = "Parses C into an AST."
repository = "http://github.com/tcr/parser-c"
homepage = "http://github.com/tcr/parser-c"
license = "MIT OR Apache-2.0"

[dependencies]
num = "0.1"
num-derive = "0.1"
bitflags = "0.9.1"
either = "1.1.0"
lazy_static = "0.2"
parser-c-macro = { path = "parser-c-macro", version = "0.2" }

[dev-dependencies]
walkdir = "1"

[profile.test]
debug = true
