// Original file: "Tokens.hs"
// File auto-generated using Corollary.

use data::position::{Position, PosLength, Pos};
use data::ident::Ident;
use syntax::constants::*;

#[derive(Clone, Debug, Pos)]
pub enum CToken {
    CTokLParen(PosLength),
    CTokRParen(PosLength),
    CTokLBracket(PosLength),
    CTokRBracket(PosLength),
    CTokArrow(PosLength),
    CTokDot(PosLength),
    CTokExclam(PosLength),
    CTokTilde(PosLength),
    CTokInc(PosLength),
    CTokDec(PosLength),
    CTokPlus(PosLength),
    CTokMinus(PosLength),
    CTokStar(PosLength),
    CTokSlash(PosLength),
    CTokPercent(PosLength),
    CTokAmper(PosLength),
    CTokShiftL(PosLength),
    CTokShiftR(PosLength),
    CTokLess(PosLength),
    CTokLessEq(PosLength),
    CTokHigh(PosLength),
    CTokHighEq(PosLength),
    CTokEqual(PosLength),
    CTokUnequal(PosLength),
    CTokHat(PosLength),
    CTokBar(PosLength),
    CTokAnd(PosLength),
    CTokOr(PosLength),
    CTokQuest(PosLength),
    CTokColon(PosLength),
    CTokAssign(PosLength),
    CTokPlusAss(PosLength),
    CTokMinusAss(PosLength),
    CTokStarAss(PosLength),
    CTokSlashAss(PosLength),
    CTokPercAss(PosLength),
    CTokAmpAss(PosLength),
    CTokHatAss(PosLength),
    CTokBarAss(PosLength),
    CTokSLAss(PosLength),
    CTokSRAss(PosLength),
    CTokComma(PosLength),
    CTokSemic(PosLength),
    CTokLBrace(PosLength),
    CTokRBrace(PosLength),
    CTokEllipsis(PosLength),
    CTokAlignof(PosLength),
    CTokAlignas(PosLength),
    CTokAsm(PosLength),
    CTokAtomic(PosLength),
    CTokAuto(PosLength),
    CTokBreak(PosLength),
    CTokBool(PosLength),
    CTokCase(PosLength),
    CTokChar(PosLength),
    CTokConst(PosLength),
    CTokContinue(PosLength),
    CTokComplex(PosLength),
    CTokDefault(PosLength),
    CTokDo(PosLength),
    CTokDouble(PosLength),
    CTokElse(PosLength),
    CTokEnum(PosLength),
    CTokExtern(PosLength),
    CTokFloat(PosLength),
    CTokFor(PosLength),
    CTokGeneric(PosLength),
    CTokGoto(PosLength),
    CTokIf(PosLength),
    CTokInline(PosLength),
    CTokInt(PosLength),
    CTokInt128(PosLength),
    CTokLong(PosLength),
    CTokLabel(PosLength),
    CTokNoreturn(PosLength),
    CTokNullable(PosLength),
    CTokNonnull(PosLength),
    CTokRegister(PosLength),
    CTokRestrict(PosLength),
    CTokReturn(PosLength),
    CTokShort(PosLength),
    CTokSigned(PosLength),
    CTokSizeof(PosLength),
    CTokStatic(PosLength),
    CTokStaticAssert(PosLength),
    CTokStruct(PosLength),
    CTokSwitch(PosLength),
    CTokTypedef(PosLength),
    CTokTypeof(PosLength),
    CTokThread(PosLength),
    CTokUnion(PosLength),
    CTokUnsigned(PosLength),
    CTokVoid(PosLength),
    CTokVolatile(PosLength),
    CTokWhile(PosLength),
    CTokCLit(PosLength, CChar),
    CTokILit(PosLength, CInteger),
    CTokFLit(PosLength, CFloat),
    CTokSLit(PosLength, CString),
    CTokIdent(PosLength, Ident),
    CTokTyIdent(PosLength, Ident),
    CTokGnuC(PosLength, GnuCTok),
    CTokClangC(PosLength, ClangCTok),
    CTokEof,
}
pub use self::CToken::*;

impl CToken {
    pub fn into_pos_len(self) -> PosLength {
        match self {
            CTokLParen(posl) => posl,
            CTokRParen(posl) => posl,
            CTokLBracket(posl) => posl,
            CTokRBracket(posl) => posl,
            CTokArrow(posl) => posl,
            CTokDot(posl) => posl,
            CTokExclam(posl) => posl,
            CTokTilde(posl) => posl,
            CTokInc(posl) => posl,
            CTokDec(posl) => posl,
            CTokPlus(posl) => posl,
            CTokMinus(posl) => posl,
            CTokStar(posl) => posl,
            CTokSlash(posl) => posl,
            CTokPercent(posl) => posl,
            CTokAmper(posl) => posl,
            CTokShiftL(posl) => posl,
            CTokShiftR(posl) => posl,
            CTokLess(posl) => posl,
            CTokLessEq(posl) => posl,
            CTokHigh(posl) => posl,
            CTokHighEq(posl) => posl,
            CTokEqual(posl) => posl,
            CTokUnequal(posl) => posl,
            CTokHat(posl) => posl,
            CTokBar(posl) => posl,
            CTokAnd(posl) => posl,
            CTokOr(posl) => posl,
            CTokQuest(posl) => posl,
            CTokColon(posl) => posl,
            CTokAssign(posl) => posl,
            CTokPlusAss(posl) => posl,
            CTokMinusAss(posl) => posl,
            CTokStarAss(posl) => posl,
            CTokSlashAss(posl) => posl,
            CTokPercAss(posl) => posl,
            CTokAmpAss(posl) => posl,
            CTokHatAss(posl) => posl,
            CTokBarAss(posl) => posl,
            CTokSLAss(posl) => posl,
            CTokSRAss(posl) => posl,
            CTokComma(posl) => posl,
            CTokSemic(posl) => posl,
            CTokLBrace(posl) => posl,
            CTokRBrace(posl) => posl,
            CTokEllipsis(posl) => posl,
            CTokAlignof(posl) => posl,
            CTokAlignas(posl) => posl,
            CTokAsm(posl) => posl,
            CTokAtomic(posl) => posl,
            CTokAuto(posl) => posl,
            CTokBreak(posl) => posl,
            CTokBool(posl) => posl,
            CTokCase(posl) => posl,
            CTokChar(posl) => posl,
            CTokConst(posl) => posl,
            CTokContinue(posl) => posl,
            CTokComplex(posl) => posl,
            CTokDefault(posl) => posl,
            CTokDo(posl) => posl,
            CTokDouble(posl) => posl,
            CTokElse(posl) => posl,
            CTokEnum(posl) => posl,
            CTokExtern(posl) => posl,
            CTokFloat(posl) => posl,
            CTokFor(posl) => posl,
            CTokGeneric(posl) => posl,
            CTokGoto(posl) => posl,
            CTokInt(posl) => posl,
            CTokInt128(posl) => posl,
            CTokInline(posl) => posl,
            CTokIf(posl) => posl,
            CTokLong(posl) => posl,
            CTokLabel(posl) => posl,
            CTokNoreturn(posl) => posl,
            CTokNullable(posl) => posl,
            CTokNonnull(posl) => posl,
            CTokRegister(posl) => posl,
            CTokRestrict(posl) => posl,
            CTokReturn(posl) => posl,
            CTokShort(posl) => posl,
            CTokSigned(posl) => posl,
            CTokSizeof(posl) => posl,
            CTokStatic(posl) => posl,
            CTokStaticAssert(posl) => posl,
            CTokStruct(posl) => posl,
            CTokSwitch(posl) => posl,
            CTokTypedef(posl) => posl,
            CTokTypeof(posl) => posl,
            CTokThread(posl) => posl,
            CTokUnion(posl) => posl,
            CTokUnsigned(posl) => posl,
            CTokVoid(posl) => posl,
            CTokVolatile(posl) => posl,
            CTokWhile(posl) => posl,
            CTokCLit(posl, _) => posl,
            CTokILit(posl, _) => posl,
            CTokFLit(posl, _) => posl,
            CTokSLit(posl, _) => posl,
            CTokIdent(posl, _) => posl,
            CTokTyIdent(posl, _) => posl,
            CTokGnuC(posl, _) => posl,
            CTokClangC(posl, _) => posl,
            CTokEof => panic!("CToken::into_pos_len: Eof"),
        }
    }
}

use std::fmt::{self, Display, Formatter};
impl Display for CToken {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        match *self {
            CTokLParen(_)         => write!(f, "("),
            CTokRParen(_)         => write!(f, ")"),
            CTokLBracket(_)       => write!(f, "["),
            CTokRBracket(_)       => write!(f, "]"),
            CTokArrow(_)          => write!(f, "->"),
            CTokDot(_)            => write!(f, "."),
            CTokExclam(_)         => write!(f, "!"),
            CTokTilde(_)          => write!(f, "~"),
            CTokInc(_)            => write!(f, "++"),
            CTokDec(_)            => write!(f, "--"),
            CTokPlus(_)           => write!(f, "+"),
            CTokMinus(_)          => write!(f, "-"),
            CTokStar(_)           => write!(f, "*"),
            CTokSlash(_)          => write!(f, "/"),
            CTokPercent(_)        => write!(f, "%"),
            CTokAmper(_)          => write!(f, "&"),
            CTokShiftL(_)         => write!(f, "<<"),
            CTokShiftR(_)         => write!(f, ">>"),
            CTokLess(_)           => write!(f, "<"),
            CTokLessEq(_)         => write!(f, "<="),
            CTokHigh(_)           => write!(f, ">"),
            CTokHighEq(_)         => write!(f, ">="),
            CTokEqual(_)          => write!(f, "=="),
            CTokUnequal(_)        => write!(f, "!="),
            CTokHat(_)            => write!(f, "^"),
            CTokBar(_)            => write!(f, "|"),
            CTokAnd(_)            => write!(f, "&&"),
            CTokOr(_)             => write!(f, "||"),
            CTokQuest(_)          => write!(f, "?"),
            CTokColon(_)          => write!(f, ":"),
            CTokAssign(_)         => write!(f, "="),
            CTokPlusAss(_)        => write!(f, "+="),
            CTokMinusAss(_)       => write!(f, "-="),
            CTokStarAss(_)        => write!(f, "*="),
            CTokSlashAss(_)       => write!(f, "/="),
            CTokPercAss(_)        => write!(f, "%="),
            CTokAmpAss(_)         => write!(f, "&="),
            CTokHatAss(_)         => write!(f, "^="),
            CTokBarAss(_)         => write!(f, "|="),
            CTokSLAss(_)          => write!(f, "<<="),
            CTokSRAss(_)          => write!(f, ">>="),
            CTokComma(_)          => write!(f, ","),
            CTokSemic(_)          => write!(f, ";"),
            CTokLBrace(_)         => write!(f, "{{"),
            CTokRBrace(_)         => write!(f, "}}"),
            CTokEllipsis(_)       => write!(f, "..."),
            CTokAlignof(_)        => write!(f, "alignof"),
            CTokAlignas(_)        => write!(f, "_Alignas"),
            CTokAsm(_)            => write!(f, "asm"),
            CTokAtomic(_)         => write!(f, "_Atomic"),
            CTokAuto(_)           => write!(f, "auto"),
            CTokBreak(_)          => write!(f, "break"),
            CTokBool(_)           => write!(f, "_Bool"),
            CTokCase(_)           => write!(f, "case"),
            CTokChar(_)           => write!(f, "char"),
            CTokConst(_)          => write!(f, "const"),
            CTokContinue(_)       => write!(f, "continue"),
            CTokComplex(_)        => write!(f, "_Complex"),
            CTokDefault(_)        => write!(f, "default"),
            CTokDo(_)             => write!(f, "do"),
            CTokDouble(_)         => write!(f, "double"),
            CTokElse(_)           => write!(f, "else"),
            CTokEnum(_)           => write!(f, "enum"),
            CTokExtern(_)         => write!(f, "extern"),
            CTokFloat(_)          => write!(f, "float"),
            CTokFor(_)            => write!(f, "for"),
            CTokGeneric(_)        => write!(f, "_Generic"),
            CTokGoto(_)           => write!(f, "goto"),
            CTokInt(_)            => write!(f, "int"),
            CTokInt128(_)         => write!(f, "__int128"),
            CTokInline(_)         => write!(f, "inline"),
            CTokIf(_)             => write!(f, "if"),
            CTokLong(_)           => write!(f, "long"),
            CTokLabel(_)          => write!(f, "__label__"),
            CTokNoreturn(_)       => write!(f, "_Noreturn"),
            CTokNullable(_)       => write!(f, "_Nullable"),
            CTokNonnull(_)        => write!(f, "_Nonnull"),
            CTokRegister(_)       => write!(f, "register"),
            CTokRestrict(_)       => write!(f, "restrict"),
            CTokReturn(_)         => write!(f, "return"),
            CTokShort(_)          => write!(f, "short"),
            CTokSigned(_)         => write!(f, "signed"),
            CTokSizeof(_)         => write!(f, "sizeof"),
            CTokStatic(_)         => write!(f, "static"),
            CTokStaticAssert(_)   => write!(f, "_Static_assert"),
            CTokStruct(_)         => write!(f, "struct"),
            CTokSwitch(_)         => write!(f, "switch"),
            CTokTypedef(_)        => write!(f, "typedef"),
            CTokTypeof(_)         => write!(f, "typeof"),
            CTokThread(_)         => write!(f, "_Thread_local"),
            CTokUnion(_)          => write!(f, "union"),
            CTokUnsigned(_)       => write!(f, "unsigned"),
            CTokVoid(_)           => write!(f, "void"),
            CTokVolatile(_)       => write!(f, "volatile"),
            CTokWhile(_)          => write!(f, "while"),
            CTokCLit(_, ref v)    => write!(f, "{}", showCChar(v)),
            CTokILit(_, ref v)    => write!(f, "{}", showCInteger(v)),
            CTokFLit(_, ref v)    => write!(f, "{}", showCFloat(v)),
            CTokSLit(_, ref v)    => write!(f, "{}", showCString(v)),
            CTokIdent(_, ref v)   => write!(f, "{}", v.as_str()),
            CTokTyIdent(_, ref v) => write!(f, "{}", v.as_str()),
            CTokGnuC(_, GnuCTok::Attr) => write!(f, "__attribute__"),
            CTokGnuC(_, GnuCTok::Ext)  => write!(f, "__extension__"),
            CTokGnuC(_, GnuCTok::VaArg)   => write!(f, "__builtin_va_arg"),
            CTokGnuC(_, GnuCTok::Offsetof) => write!(f, "__builtin_offsetof"),
            CTokGnuC(_, GnuCTok::TyCompat) => write!(f, "__builtin_types_compatible_p"),
            CTokGnuC(_, GnuCTok::ComplexReal) => write!(f, "__real__"),
            CTokGnuC(_, GnuCTok::ComplexImag) => write!(f, "__image__"),
            CTokClangC(_, ClangCTok::CVersion(ClangCVersion(ref v))) => write!(f, "{}", v),
            CTokEof               => write!(f, "<EOF>"),
        }
    }
}

#[derive(Clone, Debug)]
pub enum GnuCTok {
    Attr,
    Ext,
    VaArg,
    Offsetof,
    TyCompat,
    ComplexReal,
    ComplexImag,
}

#[derive(Clone, Debug)]
pub enum ClangCTok {
    CVersion(ClangCVersion),
}
